// Edit this file to update menu categories, items, or prices.
// Prices are in Qatari Riyal (QR). Leave descEn/descAr empty if no description needed.
const MENU_DATA = [
  {
    id: 'breakfast',
    nameEn: 'Breakfast',
    nameAr: 'الإفطار',
    items: [
      { nameEn: 'Egg Scrambled', nameAr: 'بيض مخفوق', descEn: '', descAr: '', price: 12 },
      { nameEn: 'Egg And Cheese', nameAr: 'بيض وجبنة', descEn: '', descAr: '', price: 20 },
      { nameEn: 'Eggs Boiled', nameAr: 'بيض مسلوق', descEn: '', descAr: '', price: 12 },
      { nameEn: 'Fetta Cheese', nameAr: 'جبنة فيتا', descEn: '', descAr: '', price: 19 },
      { nameEn: 'Eggs Omlette', nameAr: 'أومليت بيض', descEn: '', descAr: '', price: 18 },
      { nameEn: 'Eggs Sunny Side Up', nameAr: 'بيض مقلي', descEn: '', descAr: '', price: 12 },
      { nameEn: 'Falafel', nameAr: 'فلافل', descEn: '', descAr: '', price: 12 },
      { nameEn: 'Labneh', nameAr: 'لبنة', descEn: '', descAr: '', price: 14 },
      { nameEn: 'Foul', nameAr: 'فول', descEn: '', descAr: '', price: 15 },
      { nameEn: 'Thawani Daily Breakfast 2P', nameAr: 'إفطار ثواني اليومي لشخصين', descEn: '', descAr: '', price: 35 },
      { nameEn: 'Thawani Daily Breakfast 2P + Shisha', nameAr: 'إفطار ثواني اليومي لشخصين مع شيشة', descEn: '', descAr: '', price: 75 },
    ],
  },
  {
    id: 'soup',
    nameEn: 'Soup',
    nameAr: 'الشوربة',
    items: [
      { nameEn: 'Cream Of Chicken Soup', nameAr: 'شوربة كريمة الدجاج', descEn: '', descAr: '', price: 25 },
      { nameEn: 'Lentil Soup', nameAr: 'شوربة العدس', descEn: '', descAr: '', price: 25 },
      { nameEn: 'Mushroom Soup', nameAr: 'شوربة الفطر', descEn: '', descAr: '', price: 30 },
    ],
  },
  {
    id: 'salads',
    nameEn: 'Salads',
    nameAr: 'السلطات',
    items: [
      { nameEn: 'Chef Salad', nameAr: 'سلطة الشيف', descEn: '', descAr: '', price: 30 },
      { nameEn: 'Fattoush', nameAr: 'فتوش', descEn: '', descAr: '', price: 20 },
      { nameEn: 'Tabbouleh', nameAr: 'تبولة', descEn: '', descAr: '', price: 19 },
      { nameEn: 'Caesar Salad Chicken', nameAr: 'سلطة سيزر بالدجاج', descEn: '', descAr: '', price: 25 },
      { nameEn: 'Rocca Beetroot', nameAr: 'سلطة الجرجير والشمندر', descEn: '', descAr: '', price: 18 },
      { nameEn: 'Green Salad', nameAr: 'سلطة خضراء', descEn: '', descAr: '', price: 18 },
      { nameEn: 'Greek Salad', nameAr: 'سلطة يونانية', descEn: '', descAr: '', price: 18 },
    ],
  },
  {
    id: 'cold-appetizers',
    nameEn: 'Cold Appetizers',
    nameAr: 'المقبلات الباردة',
    items: [
      { nameEn: 'Hummus', nameAr: 'حمص', descEn: '', descAr: '', price: 20 },
      { nameEn: 'Mutabal', nameAr: 'متبل', descEn: '', descAr: '', price: 18 },
      { nameEn: 'Baba Ghanoush', nameAr: 'بابا غنوج', descEn: '', descAr: '', price: 15 },
      { nameEn: 'Grape Leaves', nameAr: 'ورق عنب', descEn: '', descAr: '', price: 17 },
      { nameEn: 'Yogurt Cucumber', nameAr: 'لبن بالخيار', descEn: '', descAr: '', price: 14 },
      { nameEn: 'Mixed Pickles', nameAr: 'مخلل مشكل', descEn: '', descAr: '', price: 12 },
      { nameEn: 'Pickled Eggplant & Tomatoes', nameAr: 'مخلل باذنجان وطماطم', descEn: '', descAr: '', price: 15 },
      { nameEn: 'Mix Platter Cold Appetizer (Small)', nameAr: 'طبق مقبلات باردة مشكلة صغير', descEn: '', descAr: '', price: 25 },
      { nameEn: 'Mix Platter Cold Appetizer (Large)', nameAr: 'طبق مقبلات باردة مشكلة كبير', descEn: '', descAr: '', price: 43 },
    ],
  },
  {
    id: 'hot-appetizers',
    nameEn: 'Hot Appetizers',
    nameAr: 'المقبلات الساخنة',
    items: [
      { nameEn: 'French Fries', nameAr: 'بطاطس مقلية', descEn: '', descAr: '', price: 10 },
      { nameEn: 'Spicy Potato', nameAr: 'بطاطس حارة', descEn: '', descAr: '', price: 15 },
      { nameEn: 'Cheese Rolls', nameAr: 'رولز جبنة', descEn: '', descAr: '', price: 20 },
      { nameEn: 'Meat Kibbeh', nameAr: 'كبة لحم', descEn: '', descAr: '', price: 25 },
      { nameEn: 'Meat Samosa', nameAr: 'سمبوسة لحم', descEn: '', descAr: '', price: 25 },
      { nameEn: 'Hummus With Lamb Meat', nameAr: 'حمص باللحم', descEn: '', descAr: '', price: 27 },
    ],
  },
  {
    id: 'sandwiches',
    nameEn: 'Sandwiches',
    nameAr: 'السندويشات',
    items: [
      { nameEn: 'Club Sandwich', nameAr: 'كلوب ساندويش', descEn: '', descAr: '', price: 20 },
      { nameEn: 'Shish Tawook Sandwich', nameAr: 'ساندويش شيش طاووق', descEn: '', descAr: '', price: 20 },
      { nameEn: 'Fajita Chicken Sandwich', nameAr: 'ساندويش فاجيتا دجاج', descEn: '', descAr: '', price: 24 },
      { nameEn: 'Kofta Lamb Sandwich', nameAr: 'ساندويش كفتة لحم', descEn: '', descAr: '', price: 25 },
      { nameEn: 'Meat Fajita Sandwich', nameAr: 'ساندويش فاجيتا لحم', descEn: '', descAr: '', price: 27 },
      { nameEn: 'Meat Cubes Sandwich', nameAr: 'ساندويش مكعبات لحم', descEn: '', descAr: '', price: 30 },
      { nameEn: 'Hawawshi Sandwich', nameAr: 'ساندويش هواوشي', descEn: '', descAr: '', price: 30 },
    ],
  },
  {
    id: 'moroccan',
    nameEn: 'Moroccan Food',
    nameAr: 'المأكولات المغربية',
    items: [
      { nameEn: 'Harira', nameAr: 'حريرة', descEn: 'Traditional Moroccan tomato & lentil soup', descAr: 'شوربة مغربية بالطماطم والعدس', price: 35 },
      { nameEn: 'Chicken Daghmira', nameAr: 'دغميرة دجاج', descEn: 'Slow-cooked chicken in a spiced sauce', descAr: 'دجاج مطبوخ ببطء بصوص متبل', price: 40 },
      { nameEn: 'Koskosi Chicken', nameAr: 'كسكسي دجاج', descEn: 'Steamed couscous with chicken', descAr: 'كسكسي بالبخار مع الدجاج', price: 40 },
      { nameEn: 'Koskosi Meat', nameAr: 'كسكسي لحم', descEn: 'Steamed couscous with lamb', descAr: 'كسكسي بالبخار مع اللحم', price: 45 },
      { nameEn: 'Barkouk', nameAr: 'بركوق', descEn: 'Lamb slow-cooked with prunes & spices', descAr: 'لحم مطبوخ ببطء مع البرقوق والبهارات', price: 50 },
      { nameEn: 'Siffa', nameAr: 'سفة', descEn: 'Sweet vermicelli with cinnamon & raisins', descAr: 'شعيرية حلوة بالقرفة والزبيب', price: 35 },
      { nameEn: 'Moshabakia', nameAr: 'مشبكية', descEn: 'Crispy fried pastry with honey', descAr: 'حلوى مقرمشة مغمورة بالعسل', price: 25 },
    ],
  },
  {
    id: 'grills',
    nameEn: 'Grills',
    nameAr: 'المشاوي',
    items: [
      { nameEn: 'Shish Tawook 300g', nameAr: 'شيش طاووق 300 غرام', descEn: '', descAr: '', price: 32 },
      { nameEn: 'Kofta 300g', nameAr: 'كفتة 300 غرام', descEn: '', descAr: '', price: 42 },
      { nameEn: 'Chicken Boneless (Half)', nameAr: 'دجاج بلا عظم (نصف)', descEn: '', descAr: '', price: 27 },
      { nameEn: 'Chicken Boneless (Whole)', nameAr: 'دجاج بلا عظم (كامل)', descEn: '', descAr: '', price: 55 },
      { nameEn: 'Shukaf 300g', nameAr: 'شكاف 300 غرام', descEn: '', descAr: '', price: 55 },
      { nameEn: 'Mix Grill 500g', nameAr: 'مشاوي مشكلة 500 غرام', descEn: '', descAr: '', price: 72 },
      { nameEn: 'Lamb Chops 350g', nameAr: 'ضلوع خروف 350 غرام', descEn: '', descAr: '', price: 95 },
      { nameEn: 'Mix Grill 1 KG', nameAr: 'مشاوي مشكلة 1 كيلو', descEn: '', descAr: '', price: 144 },
    ],
  },
  {
    id: 'manakish',
    nameEn: 'Manakish & Pies',
    nameAr: 'مناقيش وعجائن',
    items: [
      { nameEn: 'Zaatar', nameAr: 'زعتر', descEn: '', descAr: '', price: 12 },
      { nameEn: 'Spinach', nameAr: 'سبانخ', descEn: '', descAr: '', price: 14 },
      { nameEn: 'Labna With Olive', nameAr: 'لبنة مع زيتون', descEn: '', descAr: '', price: 14 },
      { nameEn: 'Meat Vegetable Dough', nameAr: 'عجين باللحم والخضار', descEn: '', descAr: '', price: 17 },
      { nameEn: 'Cheese With Eggs Pie', nameAr: 'فطيرة جبنة وبيض', descEn: '', descAr: '', price: 18 },
      { nameEn: 'Labna With Honey', nameAr: 'لبنة بالعسل', descEn: '', descAr: '', price: 18 },
      { nameEn: 'Akkawi Cheese', nameAr: 'جبنة عكاوي', descEn: '', descAr: '', price: 19 },
      { nameEn: 'Halloumi Cheese Pie', nameAr: 'فطيرة جبنة حلوم', descEn: '', descAr: '', price: 19 },
      { nameEn: 'Chicken Pie', nameAr: 'فطيرة دجاج', descEn: '', descAr: '', price: 19 },
      { nameEn: 'Maqloub Chicken', nameAr: 'مقلوبة دجاج', descEn: '', descAr: '', price: 28 },
      { nameEn: 'Makloub', nameAr: 'مقلوبة', descEn: '', descAr: '', price: 28 },
      { nameEn: 'Baguette Farsi', nameAr: 'باغيت فارسي', descEn: '', descAr: '', price: 30 },
    ],
  },
  {
    id: 'pasta',
    nameEn: 'Pasta',
    nameAr: 'المعكرونة',
    items: [
      { nameEn: 'Spaghetti Escalope', nameAr: 'سباغيتي إسكالوب', descEn: '', descAr: '', price: 28 },
      { nameEn: 'Chicken Pasta', nameAr: 'معكرونة الدجاج', descEn: '', descAr: '', price: 30 },
      { nameEn: 'Penne Arrabbiata', nameAr: 'بيني أرابياتا', descEn: '', descAr: '', price: 32 },
      { nameEn: 'Bechamel With Meat', nameAr: 'بشاميل باللحم', descEn: '', descAr: '', price: 40 },
      { nameEn: 'Spaghetti Bolognese', nameAr: 'سباغيتي بولونيز', descEn: '', descAr: '', price: 40 },
      { nameEn: 'Pasta Alfredo', nameAr: 'معكرونة ألفريدو', descEn: '', descAr: '', price: 45 },
    ],
  },
  {
    id: 'meshaltet',
    nameEn: 'Meshaltet',
    nameAr: 'مشلتت',
    items: [
      { nameEn: 'Meshaltet Nutella', nameAr: 'مشلتت نوتيلا', descEn: '', descAr: '', price: 35 },
      { nameEn: 'Meshaltet Honey Ashta', nameAr: 'مشلتت عسل وقشطة', descEn: '', descAr: '', price: 35 },
      { nameEn: 'Meshaltet Honey Kiri', nameAr: 'مشلتت عسل وكيري', descEn: '', descAr: '', price: 35 },
      { nameEn: 'Meshaltet Cheese W Egg', nameAr: 'مشلتت جبنة وبيض', descEn: '', descAr: '', price: 35 },
      { nameEn: 'Meshaltet Sojok', nameAr: 'مشلتت سجق', descEn: '', descAr: '', price: 38 },
      { nameEn: 'Meshaltet Mix Cheese', nameAr: 'مشلتت جبنة مشكلة', descEn: '', descAr: '', price: 38 },
      { nameEn: 'Meshaltet Lotus Pistachio', nameAr: 'مشلتت لوتس وفستق', descEn: '', descAr: '', price: 40 },
      { nameEn: 'Meshaltet Beef', nameAr: 'مشلتت لحم', descEn: '', descAr: '', price: 40 },
      { nameEn: 'Meshaltet Basterma', nameAr: 'مشلتت بسطرمة', descEn: '', descAr: '', price: 40 },
      { nameEn: 'Meshaltet Half', nameAr: 'مشلتت نصف', descEn: '', descAr: '', price: 40 },
      { nameEn: 'Meshaltet Beef Mix', nameAr: 'مشلتت لحم مشكل', descEn: '', descAr: '', price: 45 },
      { nameEn: 'Meshaltet Plain', nameAr: 'مشلتت سادة', descEn: '', descAr: '', price: 50 },
    ],
  },
  {
    id: 'pizza',
    nameEn: 'Pizza',
    nameAr: 'بيتزا',
    items: [
      { nameEn: 'Margherita Pizza', nameAr: 'بيتزا مارغريتا', descEn: '', descAr: '', price: 25 },
      { nameEn: 'Smoked Turkey Pizza', nameAr: 'بيتزا ديك رومي مدخن', descEn: '', descAr: '', price: 32 },
      { nameEn: 'Vegetable Pizza', nameAr: 'بيتزا خضار', descEn: '', descAr: '', price: 32 },
      { nameEn: 'Chicken Pizza', nameAr: 'بيتزا دجاج', descEn: '', descAr: '', price: 35 },
      { nameEn: 'Thawani Pizza', nameAr: 'بيتزا ثواني', descEn: '', descAr: '', price: 45 },
    ],
  },
  {
    id: 'main-course',
    nameEn: 'Main Course',
    nameAr: 'الأطباق الرئيسية',
    items: [
      { nameEn: 'Fajita Chicken Plate', nameAr: 'طبق فاجيتا دجاج', descEn: '', descAr: '', price: 28 },
      { nameEn: 'Fajita Meat Plate', nameAr: 'طبق فاجيتا لحم', descEn: '', descAr: '', price: 35 },
      { nameEn: 'Business Lunch', nameAr: 'وجبة عمل', descEn: '', descAr: '', price: 35 },
      { nameEn: 'Beef Steak Plate', nameAr: 'طبق ستيك لحم', descEn: '', descAr: '', price: 55 },
      { nameEn: 'Business Lunch + Shisha', nameAr: 'وجبة عمل مع شيشة', descEn: '', descAr: '', price: 85 },
    ],
  },
  {
    id: 'sweets',
    nameEn: 'Sweets',
    nameAr: 'الحلويات',
    items: [
      { nameEn: 'Ice Cream Vanilla', nameAr: 'آيس كريم فانيليا', descEn: '', descAr: '', price: 15 },
      { nameEn: 'Ice Cream Strawberry', nameAr: 'آيس كريم فراولة', descEn: '', descAr: '', price: 15 },
      { nameEn: 'Ice Cream Chocolate', nameAr: 'آيس كريم شوكولاتة', descEn: '', descAr: '', price: 15 },
      { nameEn: 'Rice Pudding', nameAr: 'أرز بالحليب', descEn: '', descAr: '', price: 20 },
      { nameEn: 'Mohalabiya', nameAr: 'مهلبية', descEn: '', descAr: '', price: 20 },
      { nameEn: 'Mixed Nuts', nameAr: 'مكسرات مشكلة', descEn: '', descAr: '', price: 20 },
      { nameEn: 'Moroccan Sweet', nameAr: 'حلوى مغربية', descEn: '', descAr: '', price: 20 },
      { nameEn: 'English Cake', nameAr: 'كيك إنجليزي', descEn: '', descAr: '', price: 20 },
      { nameEn: 'Om Ali', nameAr: 'أم علي', descEn: '', descAr: '', price: 25 },
      { nameEn: 'Sahlab', nameAr: 'سحلب', descEn: '', descAr: '', price: 25 },
      { nameEn: 'Fruits Salad', nameAr: 'سلطة فاكهة', descEn: '', descAr: '', price: 25 },
      { nameEn: 'Mix Fruit (Small)', nameAr: 'فاكهة مشكلة صغيرة', descEn: '', descAr: '', price: 35 },
      { nameEn: 'Mix Fruit (Large)', nameAr: 'فاكهة مشكلة كبيرة', descEn: '', descAr: '', price: 55 },
    ],
  },
  {
    id: 'soft-drinks',
    nameEn: 'Soft Drinks',
    nameAr: 'المشروبات الغازية',
    items: [
      { nameEn: 'Water Small', nameAr: 'ماء صغير', descEn: '', descAr: '', price: 5 },
      { nameEn: 'Water Large', nameAr: 'ماء كبير', descEn: '', descAr: '', price: 10 },
      { nameEn: 'Water Sparkling Small', nameAr: 'ماء غازي صغير', descEn: '', descAr: '', price: 10 },
      { nameEn: 'Pepsi', nameAr: 'بيبسي', descEn: '', descAr: '', price: 12 },
      { nameEn: 'Pepsi Diet', nameAr: 'بيبسي دايت', descEn: '', descAr: '', price: 12 },
      { nameEn: 'Pepsi Zero', nameAr: 'بيبسي زيرو', descEn: '', descAr: '', price: 12 },
      { nameEn: '7 Up', nameAr: 'سفن أب', descEn: '', descAr: '', price: 12 },
      { nameEn: '7 Up Diet', nameAr: 'سفن أب دايت', descEn: '', descAr: '', price: 12 },
      { nameEn: 'Mirinda', nameAr: 'ميرندا', descEn: '', descAr: '', price: 12 },
      { nameEn: 'Mountain Dew', nameAr: 'ماونتن ديو', descEn: '', descAr: '', price: 12 },
      { nameEn: 'Sting', nameAr: 'ستينج', descEn: '', descAr: '', price: 12 },
      { nameEn: 'Chani', nameAr: 'شاني', descEn: '', descAr: '', price: 12 },
      { nameEn: 'Kinza Cola', nameAr: 'كنزة كولا', descEn: '', descAr: '', price: 12 },
      { nameEn: 'Kinza Lemon', nameAr: 'كنزة ليمون', descEn: '', descAr: '', price: 12 },
      { nameEn: 'Kinza Berries', nameAr: 'كنزة توت', descEn: '', descAr: '', price: 12 },
      { nameEn: 'Barbican', nameAr: 'باربيكان', descEn: '', descAr: '', price: 15 },
      { nameEn: 'Red Bull', nameAr: 'ريد بول', descEn: '', descAr: '', price: 22 },
      { nameEn: 'Ice Tea Lemon', nameAr: 'آيس تي ليمون', descEn: '', descAr: '', price: 25 },
      { nameEn: 'Ice Tea Peach', nameAr: 'آيس تي خوخ', descEn: '', descAr: '', price: 25 },
      { nameEn: 'Water Sparkling Large', nameAr: 'ماء غازي كبير', descEn: '', descAr: '', price: 25 },
    ],
  },
  {
    id: 'tea',
    nameEn: 'Tea',
    nameAr: 'الشاي',
    items: [
      { nameEn: 'Black Tea', nameAr: 'شاي أسود', descEn: '', descAr: '', price: 12 },
      { nameEn: 'Karak Tea', nameAr: 'شاي كرك', descEn: '', descAr: '', price: 12 },
      { nameEn: 'Koshary Tea', nameAr: 'شاي كشري', descEn: '', descAr: '', price: 12 },
      { nameEn: 'Red Tea', nameAr: 'شاي أحمر', descEn: '', descAr: '', price: 12 },
      { nameEn: 'Green Tea', nameAr: 'شاي أخضر', descEn: '', descAr: '', price: 12 },
      { nameEn: 'Anis Tea', nameAr: 'شاي يانسون', descEn: '', descAr: '', price: 12 },
      { nameEn: 'Halba Plain', nameAr: 'حلبة سادة', descEn: '', descAr: '', price: 12 },
      { nameEn: 'Halba With Milk', nameAr: 'حلبة بالحليب', descEn: '', descAr: '', price: 12 },
      { nameEn: 'Cinnamon With Milk', nameAr: 'قرفة بالحليب', descEn: '', descAr: '', price: 12 },
      { nameEn: 'Lemon and Ginger', nameAr: 'ليمون وزنجبيل', descEn: '', descAr: '', price: 12 },
      { nameEn: 'Hibiscus (Hot)', nameAr: 'كركديه ساخن', descEn: '', descAr: '', price: 12 },
      { nameEn: 'Hibiscus (Cold)', nameAr: 'كركديه بارد', descEn: '', descAr: '', price: 15 },
      { nameEn: 'Moroccan Tea (Normal)', nameAr: 'أتاي مغربي عادي', descEn: '', descAr: '', price: 25 },
      { nameEn: 'Red Tea Pot (Small)', nameAr: 'إبريق شاي أحمر صغير', descEn: '', descAr: '', price: 25 },
      { nameEn: 'Red Tea Pot (Medium)', nameAr: 'إبريق شاي أحمر متوسط', descEn: '', descAr: '', price: 35 },
      { nameEn: 'Moroccan Tea (Medium)', nameAr: 'أتاي مغربي متوسط', descEn: '', descAr: '', price: 35 },
      { nameEn: 'Red Tea Pot (Large)', nameAr: 'إبريق شاي أحمر كبير', descEn: '', descAr: '', price: 49 },
      { nameEn: 'Moroccan Tea (Large)', nameAr: 'أتاي مغربي كبير', descEn: '', descAr: '', price: 50 },
    ],
  },
  {
    id: 'coffee',
    nameEn: 'Hot & Cold Coffee',
    nameAr: 'القهوة',
    items: [
      { nameEn: 'Espresso', nameAr: 'إسبريسو', descEn: '', descAr: '', price: 20 },
      { nameEn: 'Turkish Coffee', nameAr: 'قهوة تركية', descEn: '', descAr: '', price: 20 },
      { nameEn: 'Americano', nameAr: 'أمريكانو', descEn: '', descAr: '', price: 22 },
      { nameEn: 'Cafe Latte', nameAr: 'لاتيه', descEn: '', descAr: '', price: 25 },
      { nameEn: 'Nescafe', nameAr: 'نسكافيه', descEn: '', descAr: '', price: 25 },
      { nameEn: 'Cappuccino', nameAr: 'كابتشينو', descEn: '', descAr: '', price: 25 },
      { nameEn: 'Cortado', nameAr: 'كورتادو', descEn: '', descAr: '', price: 25 },
      { nameEn: 'Spanish Latte', nameAr: 'لاتيه إسباني', descEn: '', descAr: '', price: 25 },
      { nameEn: 'Machiatto', nameAr: 'ماكياتو', descEn: '', descAr: '', price: 25 },
      { nameEn: 'Hot Chocolate', nameAr: 'شوكولاتة ساخنة', descEn: '', descAr: '', price: 25 },
      { nameEn: 'French Coffee', nameAr: 'قهوة فرنسية', descEn: '', descAr: '', price: 25 },
      { nameEn: 'Flat White', nameAr: 'فلات وايت', descEn: '', descAr: '', price: 26 },
      { nameEn: 'Turkish Coffee Double', nameAr: 'قهوة تركية دبل', descEn: '', descAr: '', price: 28 },
      { nameEn: 'Spanish Latte (Cold)', nameAr: 'لاتيه إسباني بارد', descEn: '', descAr: '', price: 28 },
      { nameEn: 'Espresso Double', nameAr: 'إسبريسو دبل', descEn: '', descAr: '', price: 30 },
    ],
  },
  {
    id: 'juices',
    nameEn: 'Juices',
    nameAr: 'العصائر',
    items: [
      { nameEn: 'Orange Juice', nameAr: 'عصير برتقال', descEn: '', descAr: '', price: 20 },
      { nameEn: 'Strawberry Juice', nameAr: 'عصير فراولة', descEn: '', descAr: '', price: 20 },
      { nameEn: 'Carrot Juice', nameAr: 'عصير جزر', descEn: '', descAr: '', price: 20 },
      { nameEn: 'Watermelon Juice', nameAr: 'عصير بطيخ', descEn: '', descAr: '', price: 20 },
      { nameEn: 'Pineapple Juice', nameAr: 'عصير أناناس', descEn: '', descAr: '', price: 20 },
      { nameEn: 'Lemonade', nameAr: 'ليمونادة', descEn: '', descAr: '', price: 20 },
      { nameEn: 'Banana With Milk', nameAr: 'موز بالحليب', descEn: '', descAr: '', price: 20 },
      { nameEn: 'Pomegranate Juice', nameAr: 'عصير رمان', descEn: '', descAr: '', price: 20 },
      { nameEn: 'Mango Juice', nameAr: 'عصير مانجو', descEn: '', descAr: '', price: 20 },
      { nameEn: 'Cocktail Juice', nameAr: 'عصير كوكتيل', descEn: '', descAr: '', price: 25 },
      { nameEn: 'Avocado Juice', nameAr: 'عصير أفوكادو', descEn: '', descAr: '', price: 25 },
    ],
  },
  {
    id: 'mojito-milkshake',
    nameEn: 'Mojito & Milkshake',
    nameAr: 'موهيتو وميلك شيك',
    items: [
      { nameEn: 'Mojito 7Up', nameAr: 'موهيتو سفن أب', descEn: '', descAr: '', price: 25 },
      { nameEn: 'Mojito Redbull', nameAr: 'موهيتو ريد بول', descEn: '', descAr: '', price: 25 },
      { nameEn: 'Milkshake Chocolate', nameAr: 'ميلك شيك شوكولاتة', descEn: '', descAr: '', price: 27 },
      { nameEn: 'Milkshake Oreo', nameAr: 'ميلك شيك أوريو', descEn: '', descAr: '', price: 27 },
      { nameEn: 'Milkshake Mango', nameAr: 'ميلك شيك مانجو', descEn: '', descAr: '', price: 27 },
      { nameEn: 'Milkshake Strawberry', nameAr: 'ميلك شيك فراولة', descEn: '', descAr: '', price: 27 },
    ],
  },
  {
    id: 'smoothies',
    nameEn: 'Smoothies',
    nameAr: 'سموذي',
    items: [
      { nameEn: 'Strawberry Smoothie', nameAr: 'سموذي فراولة', descEn: '', descAr: '', price: 20 },
      { nameEn: 'Watermelon Smoothie', nameAr: 'سموذي بطيخ', descEn: '', descAr: '', price: 20 },
      { nameEn: 'Pinacolada Smoothie', nameAr: 'سموذي بينا كولادا', descEn: '', descAr: '', price: 20 },
      { nameEn: 'Lemon Mint Smoothie', nameAr: 'سموذي ليمون بالنعناع', descEn: '', descAr: '', price: 20 },
      { nameEn: 'Cocktail Strawberry Snow', nameAr: 'سموذي فراولة ثلج', descEn: '', descAr: '', price: 20 },
      { nameEn: 'Cocktail Banana Smoothie', nameAr: 'سموذي موز', descEn: '', descAr: '', price: 20 },
      { nameEn: 'Cocktail Four Season', nameAr: 'سموذي أربعة فصول', descEn: '', descAr: '', price: 20 },
      { nameEn: 'Mango Smoothie', nameAr: 'سموذي مانجو', descEn: '', descAr: '', price: 25 },
      { nameEn: 'Orange Smoothie', nameAr: 'سموذي برتقال', descEn: '', descAr: '', price: 25 },
      { nameEn: 'Cocktail Thawani Smoothie', nameAr: 'سموذي ثواني', descEn: '', descAr: '', price: 30 },
    ],
  },
  {
    id: 'shisha',
    nameEn: 'Shisha',
    nameAr: 'الشيشة',
    items: [
      { nameEn: 'Change Head Salloum', nameAr: 'تغيير رأس سالوم', descEn: '', descAr: '', price: 20 },
      { nameEn: 'Saloum Shisha', nameAr: 'شيشة سالوم', descEn: '', descAr: '', price: 30 },
      { nameEn: 'Change Head Muassal', nameAr: 'تغيير رأس معسل', descEn: '', descAr: '', price: 30 },
      { nameEn: 'Double Apples Shisha', nameAr: 'شيشة تفاح مزدوج', descEn: '', descAr: '', price: 50 },
      { nameEn: 'Mint Shisha', nameAr: 'شيشة نعناع', descEn: '', descAr: '', price: 50 },
      { nameEn: 'Peach Shisha', nameAr: 'شيشة خوخ', descEn: '', descAr: '', price: 50 },
      { nameEn: 'Peach With Mint Shisha', nameAr: 'شيشة خوخ بالنعناع', descEn: '', descAr: '', price: 50 },
      { nameEn: 'Grapes Shisha', nameAr: 'شيشة عنب', descEn: '', descAr: '', price: 50 },
      { nameEn: 'Grapes Mint Shisha', nameAr: 'شيشة عنب بالنعناع', descEn: '', descAr: '', price: 50 },
      { nameEn: 'Strawberry Shisha', nameAr: 'شيشة فراولة', descEn: '', descAr: '', price: 50 },
      { nameEn: 'Blueberry Shisha', nameAr: 'شيشة توت أزرق', descEn: '', descAr: '', price: 50 },
      { nameEn: 'Watermelon Shisha', nameAr: 'شيشة بطيخ', descEn: '', descAr: '', price: 50 },
      { nameEn: 'Melon Shisha', nameAr: 'شيشة شمام', descEn: '', descAr: '', price: 50 },
      { nameEn: 'Orange Shisha', nameAr: 'شيشة برتقال', descEn: '', descAr: '', price: 50 },
      { nameEn: 'Lemon Mint Shisha', nameAr: 'شيشة ليمون بالنعناع', descEn: '', descAr: '', price: 50 },
      { nameEn: 'Gum Shisha', nameAr: 'شيشة علكة', descEn: '', descAr: '', price: 50 },
      { nameEn: 'Gum Mint Shisha', nameAr: 'شيشة علكة نعناع', descEn: '', descAr: '', price: 50 },
      { nameEn: 'Gum Cinnamon Shisha', nameAr: 'شيشة علكة وقرفة', descEn: '', descAr: '', price: 50 },
      { nameEn: 'Mastic Shisha', nameAr: 'شيشة مستكة', descEn: '', descAr: '', price: 50 },
      { nameEn: 'Love Shisha', nameAr: 'شيشة لوف', descEn: '', descAr: '', price: 50 },
      { nameEn: 'Lady Killer Shisha', nameAr: 'شيشة ليدي كيلر', descEn: '', descAr: '', price: 50 },
      { nameEn: 'Mixed Fruits Shisha', nameAr: 'شيشة فواكه مشكلة', descEn: '', descAr: '', price: 50 },
    ],
  },
];
